# Generated by Django 2.0 on 2018-07-14 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cid', models.CharField(max_length=25, unique=True)),
                ('acronym', models.CharField(blank=True, max_length=10, null=True)),
                ('credits', models.IntegerField(choices=[(2, '2 Credits'), (4, '4 Credits')], default=4)),
                ('category', models.IntegerField(choices=[(1, 'CSE'), (2, 'ECE'), (3, 'MTH'), (4, 'HSS'), (5, 'BIO'), (6, 'ECO'), (7, 'OTH')], default=1)),
                ('choice_type', models.IntegerField(choices=[(1, 'Mandatory'), (2, 'Elective')], default=2)),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='kronFrame.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Offered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.PositiveSmallIntegerField(choices=[(1, 'Lecture'), (2, 'Tutorial'), (3, 'Lab')], default=1)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('areaName', models.CharField(blank=True, max_length=50, null=True)),
                ('class_day', models.PositiveSmallIntegerField(choices=[(1, 'Mon'), (2, 'Tue'), (3, 'Wed'), (4, 'Thu'), (5, 'Fri')], default=1)),
                ('start_time', models.PositiveSmallIntegerField(choices=[(1, '08:00'), (2, '08:30'), (3, '09:00'), (4, '09:30'), (5, '10:00'), (6, '10:30'), (7, '11:00'), (8, '11:30'), (9, '12:00'), (10, '12:30'), (11, '13:00'), (12, '13:30'), (13, '14:00'), (14, '14:30'), (15, '15:00'), (16, '15:30'), (17, '16:00'), (18, '16:30'), (19, '17:00'), (20, '17:30'), (21, '18:00'), (22, '18:30')], default=1)),
                ('end_time', models.PositiveSmallIntegerField(choices=[(1, '08:00'), (2, '08:30'), (3, '09:00'), (4, '09:30'), (5, '10:00'), (6, '10:30'), (7, '11:00'), (8, '11:30'), (9, '12:00'), (10, '12:30'), (11, '13:00'), (12, '13:30'), (13, '14:00'), (14, '14:30'), (15, '15:00'), (16, '15:30'), (17, '16:00'), (18, '16:30'), (19, '17:00'), (20, '17:30'), (21, '18:00'), (22, '18:30')], default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronFrame.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereqs', to='kronFrame.Course')),
                ('prerequisite', models.ManyToManyField(to='kronFrame.Course')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='offered',
            unique_together={('course', 'class_day', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='instructor',
            unique_together={('name', 'course')},
        ),
    ]
