# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronFrame', '0012_auto_20170805_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
