# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronFrame', '0013_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
